# Generated by Django 5.1.7 on 2025-03-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, default='2024-06-04T14:05:46.795894Z'),
            preserve_default=False,
        ),
    ]
